apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  containers:
    - name: web-server
      image: us-central1-docker.pkg.dev/inner-fx-398918/quickstart-docker-repo/quickstart-image:tag1
      ports:
      - containerPort: 80
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer